### ISSUE TITLE
Tinker's Tools Not Mining Fossils

### ISSUE THREAD

**Issue by MokahTGS** [iLexiconn/JurassiCraft#199]
Currently the Tinker's Construct tools mine nothing when used on fossils while other modded pickaxes work just fine.

Is this a known issue?

**Comment by airbreather** [comment]
What version have you tried this, and at what mining level?

This sounds exactly like #186, which would be fixed in any builds since March 21 @ 2:45 PM EDT.

My test case for the pull request was lining up 3 rows of blocks: Gold Ore, Iron Ore, and Fossil Ore (or whatever it was called), then seeing what a vanilla Stone Pickaxe, vanilla Iron Pickaxe, and two equivalent-level Tinker's Construct pickaxes did on each.  Before that fix: a) vanilla Stone Pickaxe and the Tinker equivalent only picked up Iron Ore and broke the others without dropping anything, b) vanilla Iron Pickaxe mined up all 3, and c) Tinker equivalent to Iron Pickaxe only mined up Gold Ore and Iron Ore.  Then after the fix, a) and b) remained unchanged, while c) worked the same as b).

Are you seeing something different?

**Comment by MokahTGS** [comment]
OK, where can I find later or the latest build?  I'm having trouble finding reliable links.

**Comment by airbreather** [comment]
The team's Jenkins server, http://jenkins.ilexiconn.net/job/JurassiCraft/, has been relatively reliable for me.
